// <auto-generated />
using System;
using InventoryAspireSample.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAspireSample.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryAspireSample.Shared.Entity.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "15-inch business laptop",
                            IsActive = true,
                            Name = "Laptop",
                            Price = 1200.00m,
                            Stock = 15
                        },
                        new
                        {
                            Id = 2,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Latest Android smartphone",
                            IsActive = true,
                            Name = "Smartphone",
                            Price = 800.00m,
                            Stock = 30
                        },
                        new
                        {
                            Id = 3,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ergonomic office chair",
                            IsActive = true,
                            Name = "Office Chair",
                            Price = 250.00m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 4,
                            Category = "Home",
                            CreatedAt = new DateTime(2025, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "LED desk lamp",
                            IsActive = true,
                            Name = "Desk Lamp",
                            Price = 40.00m,
                            Stock = 50
                        },
                        new
                        {
                            Id = 5,
                            Category = "Accessories",
                            CreatedAt = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Waterproof travel backpack",
                            IsActive = true,
                            Name = "Backpack",
                            Price = 60.00m,
                            Stock = 25
                        },
                        new
                        {
                            Id = 6,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Noise-cancelling headphones",
                            IsActive = true,
                            Name = "Headphones",
                            Price = 150.00m,
                            Stock = 40
                        },
                        new
                        {
                            Id = 7,
                            Category = "Sportswear",
                            CreatedAt = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Lightweight running shoes",
                            IsActive = true,
                            Name = "Running Shoes",
                            Price = 100.00m,
                            Stock = 35
                        },
                        new
                        {
                            Id = 8,
                            Category = "Appliances",
                            CreatedAt = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Automatic drip coffee maker",
                            IsActive = true,
                            Name = "Coffee Maker",
                            Price = 90.00m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 9,
                            Category = "Electronics",
                            CreatedAt = new DateTime(2025, 1, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Portable Bluetooth speaker",
                            IsActive = true,
                            Name = "Bluetooth Speaker",
                            Price = 70.00m,
                            Stock = 45
                        },
                        new
                        {
                            Id = 10,
                            Category = "Stationery",
                            CreatedAt = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hardcover ruled notebook",
                            IsActive = true,
                            Name = "Notebook",
                            Price = 12.50m,
                            Stock = 100
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
